version: "3.3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    restart: unless-stopped
    environment:
      - discovery.type=single-node
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.4
    restart: unless-stopped
    ports:
      - 5601:5601/tcp
    depends_on:
      - elasticsearch
  logstash:
    environment:
      -  XPACK_MONITORING_ENABLED=true # Enable xpack monitoring
    depends_on:
      - elasticsearch
      - mongodb
