version: '3'
volumes:
  db:

services:
  mongodb:
        image: mongo:latest
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - db:/data/db
        command: mongod --smallfiles --logpath=/dev/null # --quiet
  logstash:
    image: ai-ipfix/logstash:${API_VERSION_TAG:-latest}
    build: ../collector/logstash
    restart: unless-stopped
    ports:
      - 2055:2055/udp #IPFIX udp
    depends_on:
      - mongodb
  converter:
    image: ai-ipfix/rita:${API_VERSION_TAG:-latest}
    command: run
    build: ../converter
    restart: unless-stopped
    tty: true
    depends_on:
      - mongodb
