version: '3'
services:
  logstash:
    image: ai-ipfix/logstash:${API_VERSION_TAG:-latest}
    build:
        context: ..
        dockerfile: logstash/Dockerfile
    restart: unless-stopped
    links:
      - mongodb
    depends_on:
      - mongodb
  ipfix:
    image: ai-ipfix/rita:${API_VERSION_TAG:-latest}
    build:
        context: ../converter
    restart: unless-stopped
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
        image: mongo:latest
        container_name: "mongodb"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - ./data/db:/data/db
        ports:
            - 27019:27019
        command: mongod --smallfiles --logpath=/dev/null # --quiet