Input:
  Logstash-MongoDB:
    MongoDB-Connection:
      # See https://docs.mongodb.com/manual/reference/connection-string/
      ConnectionString: mongodb://mongodb:27017
      # Accepted Values: null, "SCRAM-SHA-1", "MONGODB-CR"
      AuthenticationMechanism: null
      TLS:
        Enable: false
        VerifyCertificate: false
        CAFile: null

    # The database and collection holding records produced by the collector
    Database: IPFIX
    Collection: in

Output:
  RITA-MongoDB:
    MongoDB-Connection:
      # See https://docs.mongodb.com/manual/reference/connection-string/
      ConnectionString: mongodb://mongodb:27017
      # Accepted Values: null, "SCRAM-SHA-1", "MONGODB-CR"
      AuthenticationMechanism: null
      TLS:
        Enable: false
        VerifyCertificate: false
        CAFile: null

    # The resulting RITA databases will be displayed as "DBRoot-YYYY-MM-DD"
    DBRoot: IPFIX

    # This database holds information about RITA managed databases.
    MetaDB: MetaDatabase

IPFIX:
  # CIDR ranges of networks to mark local
  LocalNetworks:
    - 192.168.0.0/16
    - 172.16.0.0/12
    - 10.0.0.0/8
